### PR TITLE
add i18n support

### PR DESCRIPTION
**Pull request by postescu**
recreate the same directory structure in **/content/[xx]**  as in **/content/en**

the **/content/de** folder is just for demo - will be removed in prod

### CODE REVIEW

**Comment by htroisi** [comment]
We need a way to switch languages. Can you add a “Language” drop-down menu next to the existing “Support” drop-down menu.

**Review by htroisi — CHANGES_REQUESTED** [review]
1. Change "en" to "English". 

2. Add the drop down menu triangle we for the "Team" page on the pixielabs.ai site:

image

3. The Language drop-down menu should support clicking anywhere within a row (not just exclusively on the text). Right now, if you click just to the right or left of the "en" text, the Language menu will close, but NOT switch to the "en" option. This bug also exists for the "Support" menu. 

image

**Review by htroisi — CHANGES_REQUESTED** [review]
Please rebase this PR to remove changes to untouched files.

**Comment by postescu** [comment]
> Please rebase this PR to remove changes to untouched files.

I do not know what to do here, sorry

**Review by aimichelle — APPROVED** [review]

**Pull request closed without merging**
